### ISSUE TITLE
Graphql mesh latest version upgrade

### ISSUE THREAD

**Issue by DevMesh18** [OpenSourceHelpCommunity/Questions#109]
I have upgraded graphql mesh to latest versions:
 "@graphql-mesh/config": "^6.1.0",
 "@graphql-mesh/graphql": "^0.29.12",
 "@graphql-mesh/openapi": "^0.31.2",
 "@graphql-mesh/runtime": "0.42.2",
 "@graphql-mesh/soap": "0.12.12"

After upgrade "const { findAndParseConfig} = require('@graphql-mesh/config');" is not available to load the .meshrc.yaml file.

It is throwing error findAndParseConfig if not defined.

**Comment by DevMesh18** [comment]
Now Soap request object is having issue :

URI is missing in soap request object

**Comment by gilgardosh** [comment]
It seems `@graphql-mesh/cli` is not on your dependencies list.

Try adding it (`yarn add @graphql-mesh/cli`).
If error still occurs - could you provide some more info, starting with the error message?

**Comment by DevMesh18** [comment]
Thanks @gilgardosh , You are right after adding this issue is resolved.
Apparently it is moved to cli package from config in new versions.

**Comment by DevMesh18** [comment]
Newer version of graphql-mesh/soap not returning soap schema in handlers file.

**Comment by gilgardosh** [comment]
Hi @DevMesh18 ,
I'm not sure I follow what you want to achieve here.
1. Could you make sure your Mesh dependencies are updated to latest?
2. Can you create a minimal reproduction of this issue? You can use [StackBlitz](https://stackblitz.com/) or [CodeSandbox](https://codesandbox.io/) for that

**Comment by DevMesh18** [comment]
Hello,

I am using a soap here in resolver: In below resolver "MySoap" is undefined.

`const moment = require('moment');
const { ApolloServer, gql, withFilter }  = require('apollo-server-express');
const services = require('./../services/services');

const resolvers = {
  Mutation: {
    testEvent: (root, args, {MySoap}) => {
      **console.log(MySoap) // it is undefined**
    }
  }
};
 
module.exports = { resolvers };`

and my mesharc.yaml file is:
`sources:
 - name: MySoap
   handler:
     soap:
       wsdl: http://localhost:8088/mockOutputEventServicePortBinding?WSDL
       basicAuth:
         username: username
         password: password
 
additionalResolvers:
  - ./resolvers/resolvers.js`.

It was working with old dependencies.

**Comment by DevMesh18** [comment]
Added code on page.

Thanks



Sent from App for Gmail


Monday, 12 September 2022, 11:36 +0530 from ***@***.***  ***@***.***>:

**Comment by gilgardosh** [comment]
From those partial code it's hard to figure out what's the cause.
Please set up a basic reproduction as I mentioned so we could find what causes this issue.

**Comment by DevMesh18** [comment]
Added code on git. Please let me know it is accessible or not.

[https://github.com/DevMesh18/test-soap](https://github.com/DevMesh18/test-soap)

refer server/resolver.js file where MySaop is undefined and it is defined in .meshrc.yaml file.

**Comment by gilgardosh** [comment]
I am sorry, but this reproduction is still partial and doesn't reproduce the error.
You can have a look at the examples on Mesh repo to see how things are configured there. Here is an example with additional resolvers, you can see that when configed well, context does contains the sources SDL.

I suggest you try yourself:
1. As mentioned, upgrade all Mesh depepdencies to latest. Also remove the redundant ones.
2. Add `DEBUG=1` before the execute command (e.g `DEGUG=1 yarn start`). It'll add dev data to the console

For me to further help, set up an actual reproduction that examples the error.

**Comment by DevMesh18** [comment]
Its added on sandbox. Use command from server directory to run:
> node index.js

call operation in sandbox object browser.
query {
  greeting
}

logs will print "undefined" from console.log(MySoap).

[https://codesandbox.io/p/github/DevMesh18/test-soap/csb-jztll0/draft/cranky-diffie?file=%2Fserver%2Fresolver.js&selection=%5B%7B%22endColumn%22%3A13%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A13%2C%22startLineNumber%22%3A5%7D%5D](https://codesandbox.io/p/github/DevMesh18/test-soap/csb-jztll0/draft/cranky-diffie?file=%2Fserver%2Fresolver.js&selection=%5B%7B%22endColumn%22%3A13%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A13%2C%22startLineNumber%22%3A5%7D%5D)
