### ISSUE TITLE
Please write the code for-- 

### ISSUE THREAD

**Issue by ghost** [OpenSourceHelpCommunity/Questions#193]
New post HTML Link( Hyperlink) with title automatic add in previous post in middle of content In wordpress website
 like Also read- [epicnewsnation.com](https://epicnewsnation.com/)

 thank you

**Comment by skkatiyar** [comment]
> New post HTML Link( Hyperlink) with title automatic add in previous post in middle of content In wordpress website like Also read- [epicnewsnation.com](https://epicnewsnation.com/)
> 
> thank you
