### ISSUE TITLE
[beginners] How to start contributing to OpenSource Project? 

### ISSUE THREAD

**Issue by anupammajhi** [OpenSourceHelpCommunity/Questions#2]
- [ ] What skills are required before anyone can start contributing?
- [ ] How to determine/find projects to contribute?
- [ ] How to know what to contribute exactly?
- [ ] Any tips for beginners?

**Comment by sara-02** [comment]
@anupammajhi it would be better if you can create a separate issue for each question, that way answering and tracking them will become easier.

**Comment by anupammajhi** [comment]
@sara-02 Suggestion taken!
