### ISSUE TITLE
MySQL: How to get certain row data in each group?

### ISSUE THREAD

**Issue by mountiv** [OpenSourceHelpCommunity/Questions#255]
Hello community!
I love MySQL, but faced a blocking point a few days ago, and tried to find the solution on Google but couldn't find the right one.
This is the right time when I need your help.

Table named as **worked_day** is saving the data employees working information.
Employees can work on different floor in different day.
And their can wear the different colors.

<h4>The table's design:</h4>

![image](https://user-images.githubusercontent.com/121834775/220000738-7ce87caa-cfeb-40d0-8f13-d26609d55c7f.png)

<h4>Table data in sample:</h4>

![image](https://user-images.githubusercontent.com/121834775/220054587-f2be961e-c42e-41e3-b0db-0ba51d30bf23.png)

<h4>I stopped with following query.</h4>

```
SELECT `id`, `name`, `floor`, MAX(`days`)-MIN(`days`)+1 AS `worked_days`, `suit_color` FROM `worked_day` GROUP BY `name`, `floor`
```

![image](https://user-images.githubusercontent.com/121834775/220001129-dd5daafa-f0fd-410b-8392-6f983e56943d.png)

But this is not desired result.
Set the date range, and get employees work information with his/her name, floor, worked day, the color of suit in every floor(if it is null, to get last date's color).
In above result, the **suit_color** is the first day's color not last day's color and want to get following result.

![image](https://user-images.githubusercontent.com/121834775/220002150-ef61b71a-ff84-44b7-84c8-f2572acea1f4.png)

MySQL version: 5.5

**Comment by webmaster1022** [comment]
Hi, How are you?

Try this query.

```
SELECT `worked_day1`.`name`, `worked_day1`.`floor`,`worked_day1`.`worked_days`, `worked_day2`.`suit_color` 
FROM (SELECT `name`, `floor`, MAX(`days`)-MIN(`days`)+1 AS `worked_days` FROM `worked_day` GROUP BY `name`, `floor`) AS worked_day1 
JOIN (SELECT `name`, `floor`, `suit_color` FROM (SELECT * FROM `worked_day` ORDER BY `date` DESC) AS `worked_day3` WHERE `suit_color`!='' GROUP BY `name`, `floor`) AS worked_day2 
WHERE `worked_day1`.`name` = `worked_day2`.`name` AND `worked_day1`.`floor` = `worked_day2`.`floor`
```

**Comment by mountiv** [comment]
Hello, @webmaster1022 

It works well.

Thanks.
