### ISSUE TITLE
We can add other projects too beginner level django projects ? 

### ISSUE THREAD

**Issue by anweshknayak** [OpenSourceHelpCommunity/Questions#8]
Thoughts @tapasweni-pathak

**Comment by tapasweni-pathak** [comment]
Sorry, I did not get your question, can you please elaborate a bit more?

**Comment by nikhita** [comment]
@anweshknayak Would love to answer your question but I sure of what it really meant. If you could re-phrase it, that would be awesome! :smile:

**Comment by muddlebee** [comment]
Hey I meant if we can link our projects to this community. Seems like there is already https://github.com/OpenSourceHelpCommunity/ContributingToMyProject.  :)
